# this sets the logger level (true = info, false = debug)
production: false

operator_address: 0x860B6912C2d0337ef05bbC89b0C2CB6CbAEAB4A5

# EigenLayer Slasher contract address

# This is the address of the slasher which is deployed in the anvil saved state
# The saved eigenlayer state is located in tests/integration/eigenlayer-deployed-anvil-state.json
el_slasher_address: 0x5FC8d32690cc91D4c39d9d3abcBD16989F875707
bls_operator_state_retriever_address: 0x4c5859f0F772848b2D91F1D83E2Fe57935348029
avs_service_manager_address: 0xc3e53F4d16Ae77Db1c982e75a937B9f60FE63690
bls_public_key_compendium_address: 0x59b670e9fA9D0A427751Af201D676719a970857b


# ETH RPC URL
eth_rpc_url: http://host.docker.internal:8545

eth_ws_url: ws://host.docker.internal:8545

# If you running this using eigenlayer CLI and the provided AVS packaging structure, 
# this should be /operator_keys/ecdsa_key.json as the host path will be asked while running
#
# If you are running locally using go run main.go, this should be full path to your local ecdsa key file
ecdsa_private_key_store_path: /operator_keys/ecdsa_key.json

# If you running this using eigenlayer CLI and the provided AVS packaging structure, 
# this should be /operator_keys/bls_key.json as the host path will be asked while running
#
# If you are running locally using go run main.go, this should be full path to your local bls key file
bls_private_key_store_path: /operator_keys/bls_key.json

aggregator_server_ip_port_address: host.docker.internal:8090

# This is the address of the service where metrics are exposed
eigen_metrics_ip_port_address: localhost:9090

# If you want to use the instrumented eth client, set this to true
use_instrumented_eth_client: false